db:
  username: ${username.value:postgres}
  password: pass
  driver: org.postgresql.Driver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  properties:
    first: 123
    second: 567
    third.value: Third
  pool:
    size: 12
    timeout: 10
    
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2


logging:
    level:
      root: WARN
      com.dmdev.spring.database.pool.ConnectionPool: INFO
  